- name: Fedora Playbook
  hosts: localhost

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Handle Config Files
      ansible.builtin.include_tasks: tasks/configs.yml
    - name: Add Repositories
      ansible.builtin.include_tasks: tasks/repos.yml
    - name: Install Packages
      ansible.builtin.include_tasks: tasks/packages.yml
    - name: Setup Shell
      ansible.builtin.include_tasks: tasks/shell.yml
      
