- name: Install Dnf Packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ repo_packages }}"

- name: Install Flatpacks
  ansible.builtin.shell: "flatpak install {{ item }} -y"
  loop: "{{ flatpacks }}"

- name: Install Other Packages Root
  ansible.builtin.shell: "{{ item.command }}"
  args:
    executable: "{{ item.exec }}"
  loop: "{{ other_packages_root }}"

- name: Install Other Packages User
  ansible.builtin.shell: "{{ item.command }}"
  args:
    executable: "{{ item.exec }}"
  loop: "{{ other_packages_user }}"
  become: false