- name: Exec Shell Commands
  ansible.builtin.shell: "{{ item }}"
  args:
    executable: /usr/bin/fish
  loop: "{{ shell_commands }}"
  become: true

- name: Set Fish Shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "/usr/bin/fish"
    state: present